# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: editor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65\x64itor.proto\x12\x06\x65\x64itor\"_\n\x07\x43ommand\x12\x1f\n\x04type\x18\x01 \x01(\x0e\x32\x11.editor.Operation\x12\x10\n\x08position\x18\x02 \x01(\r\x12\x11\n\ttimeStamp\x18\x03 \x01(\r\x12\x0e\n\x06userID\x18\x04 \x01(\r\"\x1f\n\rCommandStatus\x12\x0e\n\x06status\x18\x01 \x01(\r*\x1d\n\tOperation\x12\x07\n\x03INS\x10\x00\x12\x07\n\x03\x44\x45L\x10\x01\x32\x41\n\x06\x45\x64itor\x12\x37\n\x0bSendCommand\x12\x0f.editor.Command\x1a\x15.editor.CommandStatus\"\x00\x42\x06\xa2\x02\x03\x45\x44Tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'editor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\242\002\003EDT'
  _globals['_OPERATION']._serialized_start=154
  _globals['_OPERATION']._serialized_end=183
  _globals['_COMMAND']._serialized_start=24
  _globals['_COMMAND']._serialized_end=119
  _globals['_COMMANDSTATUS']._serialized_start=121
  _globals['_COMMANDSTATUS']._serialized_end=152
  _globals['_EDITOR']._serialized_start=185
  _globals['_EDITOR']._serialized_end=250
# @@protoc_insertion_point(module_scope)
